app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('api/v1', include('authentication.urls')),
    
    path('', views.home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('products/list/', views.ProductListView.as_view(), name='product_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/detail/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:ok>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
    
    path('api/v1/products/', views.ProductCreateListAPIView.as_view(), name='product-create-list-api-view'),
    path('api/v1/products/<int:pk>/', views.ProductRetrieveUpdateDestroyAPIView.as_view(), name='product-detail-api-view'),

]

brands/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return self.name    

products/models.py
from django.db import models
from categories.models import Category
from brands.models import Brand


class Product(models.Model):
    title = models.CharField(max_length=500)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='products')
    description = models.TextField(null=True, blank=True)
    serie_number = models.CharField(max_length=200, null=True, blank=True)
    cost_price = models.DecimalField(max_digits=20, decimal_places=2)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title

products/forms.py
from django import forms
from . import models


class ProductForm(forms.ModelForm):
    
    class Meta:
        model = models.Product
        fields = ['title', 'category', 'brand', 'description', 'serie_number', 'cost_price', 'selling_price']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'brand': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'serie_number': forms.TextInput(attrs={'class': 'form-control', 'rows': 3}),
            'cost_price': forms.NumberInput(attrs={'class': 'form-control', 'rows': 3}),
            'selling_price': forms.NumberInput(attrs={'class': 'form-control', 'rows': 3}),
        }
        labels = {
            'title': 'Fornecedor',
            'category': 'Produto',
            'brand': 'Quantidade',
            'description': 'Descrição',
            'serie_number': 'Numero de serie',
            'cost_price': 'Preço de custo',
            'selling_price': 'Preço de venda',
        }

products/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.db.models.query import QuerySet
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from . import models, forms, serializers
from app import metrics
from categories.models import Category
from brands.models import Brand


class ProductListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Product
    template_name = 'product_list.html'
    context_object_name = 'products'
    paginate_by = 3
    permission_required = 'products.view_product'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        title = self.request.GET.get('title')
        serie_number = self.request.GET.get('serie_number')
        category = self.request.GET.get('category')
        brand = self.request.GET.get('brand')
        
        if title:
            queryset = queryset.filter(title_icontains=title)
            
        if serie_number:
            queryset = queryset.filter(serie_number__icontains=serie_number)

        if category:
            queryset = queryset.filter(category_id=category)
            
        if brand:
            queryset = queryset.filter(brand_id=brand)
                
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_metrics'] = metrics.get_product_metrics()
        context['category'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        return context
    
class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Product
    template_named = 'product_create.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')
    permission_required = 'products.add_product'
    
    
class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Product
    template_name = 'product_detail.html'
    permission_required = 'products.view_product'
    
    
class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.Product
    template_name = 'product_update.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')
    permission_required = 'products.change_product'
    
    
class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('product_list')
    permission_required = 'products.delete_product'
    
    
class ProductCreateListAPIView(generics.ListCreateAPIView):
    queryset = models.Product.objects.all()
    serializer_class = serializers.ProductSerializer
    
    
class ProductRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Product.objects.all()
    serializer_class = serializers.ProductSerializer

products/templates/product_create.html
{% extends 'base.html' %}

{%block content %}

<div  class="container mt-4">
   <h3 class="display-6">Cadastrar Produto</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Produto</button>
            </form>
        </div>
    </div>
    <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar para lista de produtos</a>
</div>

{% endblock %}

products/templates/product_delete.html
{% extends 'brand.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Deletar Produto</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja excluir esse produto <strong>{{ object.title }}</strong>?</p>

                <form method="post">
                    {% crsf_token %}
                    <button type="submit" class="btn btn-secondary mt-3">Deletar</button>
                </form>
                <a href="{% url 'produto_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar para lista de produto</a>
            </div>
        </div>

    </div>

{% endblock %}

products/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-4">Detalhes do Produto</h3>

    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{ object.title }}</h3>
        <p class="card-text">Categoria: {{ object.category }}</p>
        <p class="card-text">Marca: {{ object.brand }}</p>
        <p class="card-text">{{ object.description }}</p>
        <p class="card-text">Número de Série: <strong>{{ object.serie_number }}</strong></p>
        <p class="card-text">Preço de Custo: <strong>R$ {{ object.cost_price }}</strong></p>
        <p class="card-text">Preço de Venda: <strong>R$ {{ object.selling_price }}</strong></p>
        <p class="card-text">Quantidade em Estoque: <strong>{{ object.quantity }}</strong></p>
      </div>
    </div>

    <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Voltar para a Lista de Produtos</a>
  </div>
{% endblock %}

products/templates/product_list.html
{% extends 'base.html' %}

{% block title %}
SGE - Marcas
{% endblock %}

{% block content %}

<div class="row mb-3">
  <div class="col-md-6">
    <form method="get" action="{% url 'brand_list' %}">
      <div class="input-group">
        <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
        <button type="submit" class="btn btn-primary">
          <i class="bi bi-search"></i>
        </button>
      </div>
    </form>
  </div>
  {% if perms.brands.add_brand %}
  <div class="col-md-6">
    <a href="{% url 'brand_create' %}" class="btn btn-success float-end">
      <i class="bi bi-plus"></i> Nova Marca
    </a>
  </div>
  {% endif %}
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for brand in brands %}
      <tr>
        <td>
          <a href="{% url 'brand_detail' brand.id %}" class="text-primary fw-semibold">
            {{ brand.id }}
          </a>
        </td>
        <td>{{ brand.name }}</td>
        <td>{{ brand.description }}</td>
        <td>
          <a href="{% url 'brand_detail' brand.id %}" class="btn btn-info btn-sm">
            <i class="bi bi-eye"></i>
          </a>

          {% if perms.brands.change_brand %}
          <a href="{% url 'brand_update' brand.id %}" class="btn btn-warning btn-sm">
            <i class="bi bi-pencil"></i>
          </a>
          {% endif %}

          {% if perms.brands.delete_brand %}
          <a href="{% url 'brand_delete' brand.id %}" class="btn btn-danger btn-sm btn-delete">
            <i class="bi bi-trash"></i>
          </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}

products/templates/product_update.html
{% extends 'base.html' %}

{% block content %}
<div class="conteiner mt-4">
    <h3 class="display-4">Ediatr Produto</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Produto</button>
            </form>
        </div>
    </div>
    <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar para lista de produtos</a>
</div>

{% endblock %}